public class Calculator {
    integer a = 10;
    integer b = 20;
    
    public void getsum() {
        integer res = a+b;
        system.debug('Result is = '+ res);
    }
    public void getmulti() {
        integer res = a*b;
        system.debug('Result is = '+ res);
    }
    public void getsub() {
        integer res = a-b;
        system.debug('Result is = '+ res);
    }
    public void getdivision() {
        integer res = a/b;
        system.debug('Result is = '+ res);
    }
    
    

}